server:
  port: 20101
  servlet:
    context-path: /
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      naming:
      # 映射命名策略：无修改命名(保留数据库驼峰式表名)
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: lsw123..
    initial-size: 5
    max-active: 20
    validationQuery: select 'x'
    validationQueryTimeout: 3
swagger:
  enable: true
  packageScan: myAdmin
  title: 后台管理接口测试
  description: 后台管理接口测试
  version: 0.0.1-SNAPSHOT
#后台管理配置
admin:
  secretKey: Mlu07sC7ScoXeZecaEYXodXib4YmZhAb
  # token有效时间，秒
  expires: 1800
  # 密码加密的加盐值
  salt: sb0EbMvyEg2hUerbXYJlAR3Chup0JrzE
  aesKey: 5SxEFRITo7X6SRcqqD6gKNxN1bbs5wlI
  authorityKey: Authority_
  userId: user_id
  initPassword: 123.?012